### ISSUE TITLE
Thread deleted?

### ISSUE THREAD

**Issue by Crayder** [urShadow/Pawn.CMD#1]
I completely understand why your last threads were deleted, but this one was perfectly fine.

You didn't go against any rules this time, so why was it deleted?

-------------

Plus, my last post was pretty important. Did you see it by any chance?

**Comment by urShadow** [comment]
I was banned again. Reason: ban evasion. 

Soon i update the plugin.

**Comment by urShadow** [comment]
Could you create and control the thread on forum.sa-mp.com instead me?

**Comment by Crayder** [comment]
Lol, I didn't even know you could ban evade on the forum...

I might do the thread.

**Comment by urShadow** [comment]
I will be grateful.

**Comment by Crayder** [comment]
Ok, yeah I'll do the thread. Can you give me what you want it to say?

I'll also have to note that I'm posting it for you.

**Comment by urShadow** [comment]
https://gist.github.com/urShadow/8cd25c312f7782a8b0f75171edca7d85

**Comment by Crayder** [comment]
Great, I'll post it soon

**Comment by JernejL** [comment]
Crayder: urshadow has a repository for a fake players plugin, not exactly what's allowed on the sa-mp forums. He was banned for a reason, and with releasing pawn.cmd, he was linking to his repository with his fake players plugin again (and was found to be ban evading).. i would not post a thread to this again, the pawn.cmd might be a good extension, but i wouldn't asociate myself with a fake players plugin. please don't post thread to his stuff at least until urshadow considers his priorities on what things to release / create and sorts out his ban on forums. 
 
common sense, guys.

**Comment by urShadow** [comment]
I agree remove repository with prohibited FakeOnline if unban me on the forum and will permit me create of the new good plugins as Pawn.CMD. Who can pass this to administration?

**Comment by Crayder** [comment]
http://forum.sa-mp.com/showthread.php?p=3710174

Posted, didn't mean to take so long... xD

**Comment by Crayder** [comment]
![image](https://cloud.githubusercontent.com/assets/9919010/15773520/53b785a0-2945-11e6-8df5-bb5280baa081.png)

**Comment by urShadow** [comment]
Will he unban my account after removing?

**Comment by Crayder** [comment]
That was not mentioned, perhaps you should ask on the IRC. I linked it above.

I'm pretty sure dugi would reply pretty soon there, he usually does when he's definitely online.

**Comment by urShadow** [comment]
"Your repository "urShadow/FakeOnline" was successfully deleted."

**Comment by urShadow** [comment]
Will you create a topic again?

**Comment by Crayder** [comment]
Perhaps you can yourself. Ask him about your ban.

**Comment by urShadow** [comment]
Thanks you, my thread has been restored.

http://forum.sa-mp.com/showthread.php?s=407bdf20fff4f94c595d185d3f514ab4&t=608474

**Comment by Crayder** [comment]
indeed.

**Comment by Crayder** [comment]
Lol, the current activity says your are "moderating" in italics...

![image](https://cloud.githubusercontent.com/assets/9919010/15774087/8bc6f874-2948-11e6-8fa1-455e44474b6b.png)

I guess that is the signal that you are unbanned?

**Comment by urShadow** [comment]
![image](https://cloud.githubusercontent.com/assets/13824389/15774408/c6a9a72a-2984-11e6-8b36-3cc7389c09e7.png)
