### ISSUE TITLE
Pawn.CMD alias error VSCODE + PAWNCC [error 010: invalid function or declaration]

### ISSUE THREAD

**Issue by ArchieQQ** [urShadow/Pawn.CMD#12]
**compiler**
![2](https://user-images.githubusercontent.com/39820747/45606610-35a52c00-ba4f-11e8-9194-88dca071e3a5.png) 
 **error**
![default](https://user-images.githubusercontent.com/39820747/45606611-35a52c00-ba4f-11e8-8cdd-97b797923a71.png)

**Comment by urShadow** [comment]
Try to remove a semicolon.

**Comment by ArchieQQ** [comment]
> Try to remove a semicolon.

it's working. Thanks 👍
