### ISSUE TITLE
putting cmds into different files results in command not getting declared

### ISSUE THREAD

**Issue by michael-fa** [urShadow/Pawn.CMD#14]
I have diffrent commands in different files stored.. say, in my main gm I include commands/main, in which I  then include "commands/supporter", "commands/admin", "commands/highadmin"... .pwn files 
after I included all files, I put the two callbacks at the end of commands/main.pwn - but calling my cmd results in invalid command message (flags always 0, seems the command isn't really declared.

```//Commands
#include "/../../gamemodes/commands/debug.pwn"
//#include "/../../gamemodes/commands/player.pwn"
//#include "/../../gamemodes/commands/supporter.pwn"
//#include "/../../gamemodes/commands/admin.pwn"
#include "/../../gamemodes/commands/head-admin.pwn"
//#include "/../../gamemodes/commands/projektleiter.pwn"*/

`public OnPlayerCommandReceived(playerid, cmd[], params[], flags)
{
	if(!pInfo[playerid][loggedin])return 0;
	DebugPrint("if([%d]%d < %d", playerid, pPermissions[playerid], flags);
    if (pPermissions[playerid]<flags)
    {
    	SendClientMessage(playerid, GREY, "* Du hast keinen Zugriff auf diesen Befehl.");
        return 0;
    }

    return 1;
}

public OnPlayerCommandPerformed(playerid, cmd[], params[], result, flags)
{
	if(result == -1)
    {
        SendClientMessage(playerid, 0xFFFFFFFF, "SERVER: Unbekannter Befehl. ("HTML_RED"/help"#HTML_WHITE")");
        return 0;
    }
	return 1;
}
```

**Comment by Crayder** [comment]
@michael-fa If you solved your issue you should explain how so other users who come across this will know what to do.

**Comment by michael-fa** [comment]
@Crayder Wow, no, I really could not get behind the weirdness the plugin reached by just putting a command in to a different file, which I then just include.

For everyone: I did not solve the problem, sadly I had to use something else (for now.)
