### ISSUE TITLE
Incompatible with YSI (y_hooks)

### ISSUE THREAD

**Issue by AliLogic** [urShadow/Pawn.CMD#15]
I'm using the latest version of Pawn.CMD (3.2.0) with YSI (4.0). I've a modular gamemode and the hooked callbacks won't work because I've to use 'Cmd' instead of 'Command' when hooking since Pawn doesn't support function names of more than 32 characters.

**Comment by George480** [comment]
I came across this problem today. I wanted to hook and use `OnPlayerCommandReceived` with two different modules (`account - not logged in` and `staff - not authorized`) but callbacks will not be called at all. 
```Pawn
#include <YSI_Coding\y_hooks>

hook OnPlayerCommandReceived(playerid, cmd[], params[], flags)
{
    print("staff:OnPlayerCommandReceived");
    return 1;
}
```
It does not print but changing back to `public` function, it prints.

**Comment by Crayder** [comment]
How about if you simply add a blank one somewhere that is a public. Before the hooks.
```
public OnPlayerCommandReceived(playerid, cmd[], params[], flags)
{
    return 1;
}
```

**Comment by George480** [comment]
Added a blank public function before the hooks, the hooks are not called. I also tried changing the include order (Pawn.CMD first and then YSI) but it made no difference.

**Comment by AliLogic** [comment]
This will never be compatible with y_hooks because it was never made with compatibility for it in mind.

**Comment by AliLogic** [comment]
The plugin code will need to be changed for that as far as I can remember about it, it caches the command names and thus, whole thing becomes incompatible at this point.

**Comment by George480** [comment]
Using the ALS method 7 in these two modules now calls `OnPlayerCommandReceived` correctly in both of them. The problem is in YSI.

**Comment by AliLogic** [comment]
That's weird, it never worked for me back in the day with either of it.
