### ISSUE TITLE
cant build with VS2019

### ISSUE THREAD

**Issue by jimsktsmith** [urShadow/Pawn.CMD#17]
+ __thiscall can only appear on nonstatic member function declarations
+ argument of type "void *" is incompatible with parameter of type "urmem::address_t"			
+ 'bool urmem::sig_scanner::init(urmem::address_t)': cannot convert argument 1 from 'void *' to 'urmem::address_t'	
![image](https://user-images.githubusercontent.com/55434995/80279585-e9d95f00-8728-11ea-9c96-18a189771b37.png)
![image](https://user-images.githubusercontent.com/55434995/80279591-f2319a00-8728-11ea-8346-d3697d693ede.png)

**Comment by jimsktsmith** [comment]
help

**Comment by urShadow** [comment]
Fixed.

https://github.com/urShadow/Pawn.CMD/commit/64072253c0eb97496ae5c94810895c4065801bcc
