### ISSUE TITLE
Invalid function or declaration

### ISSUE THREAD

**Issue by Walter-Correa** [urShadow/Pawn.CMD#20]
alias:

**Comment by urShadow** [comment]
You should provide more information.

**Comment by Walter-Correa** [comment]
> You should provide more information.

Its simple... after last update the function alias is getting error on compile.

**Comment by urShadow** [comment]
> Semicolons at the end of alias and flags declarations not allowed now

**Comment by Walter-Correa** [comment]
> > Semicolons at the end of alias and flags declarations not allowed now

But how to use alias for my cmds?

**Comment by urShadow** [comment]
https://github.com/urShadow/Pawn.CMD/pull/19

**Comment by Walter-Correa** [comment]
> #19

So is it to put at the beginning?

**Comment by urShadow** [comment]
> Just delete these semicolons at the end.

**Comment by urShadow** [comment]
The problem is solved?

**Comment by Walter-Correa** [comment]
> The problem is solved?

Fixed, thank you!
