### ISSUE TITLE
 invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by qSorin** [urShadow/Pawn.CMD#22]
I have a warrning/error in samp-server.exe !
![image](https://user-images.githubusercontent.com/63189561/83449416-416f9680-a45c-11ea-9537-5840bb224a32.png)

And if I type any command gives me the Unknown Command

I used a lastest version of Pawn.CMD
P.S: Sorry for my bad english !

**Comment by urShadow** [comment]
Windows?

**Comment by qSorin** [comment]
Yea. I have windows 10.

**Comment by urShadow** [comment]
https://github.com/urShadow/Pawn.CMD/releases/tag/3.3.1
