### ISSUE TITLE
Alias and ISO 8859-1 encoding: "ToLower: bad conversion", "ToLower: wstring_convert::from_bytes"

### ISSUE THREAD

**Issue by Autorojo** [urShadow/Pawn.CMD#23]
I'm getting errors in command aliases since 3.3.0.

For example, this code:

```C
CMD:test(playerid, params[])
{
	SendClientMessage(playerid, -1, "OK");
	return 1;
}

alias:test("tést", "teñst")
```

Works fine on a gamemode/filterscript with UTF-8 encoding. But in a ISO 8859-1 encoding gamemode it returns these errors:
- "ToLower: bad conversion" (Windows)
- "ToLower: wstring_convert::from_bytes" (Linux)

And the callback `OnPlayerCommandReceived` sometimes cuts the `cmd[]` string. So, if the command it's something like `/hellowórld`, the callback returns a `cmd[]` string like `hellow`.

I tried using `LocaleName = "es_ES.ISO8859-1"` in `pawncmd.cfg` but it does nothing.

**Comment by urShadow** [comment]
> Works fine on a gamemode/filterscript with UTF-8 encoding. But in a ISO 8859-1 encoding gamemode it returns these errors

Why can't you just use UTF-8 encoding?

**Comment by urShadow** [comment]
Try that, please.

[pawncmd.zip](https://github.com/urShadow/Pawn.CMD/files/4729685/pawncmd.zip) (commit https://github.com/urShadow/Pawn.CMD/commit/01a9ae4219e74302853c74fdc9e4723421530f67)

**Comment by Autorojo** [comment]
> Try that, please.
> 
> [pawncmd.zip](https://github.com/urShadow/Pawn.CMD/files/4729685/pawncmd.zip) (commit [01a9ae4](https://github.com/urShadow/Pawn.CMD/commit/01a9ae4219e74302853c74fdc9e4723421530f67))

That works perfect with the properly ``LocaleName`` configuration in ``pawncmd.cfg``.

It seems to be solved. Great job!

**Comment by urShadow** [comment]
Fixed.

https://github.com/urShadow/Pawn.CMD/releases/tag/3.3.3
