### ISSUE TITLE
invalid unordered_map<K, T> key

### ISSUE THREAD

**Issue by qSorin** [urShadow/Pawn.CMD#25]
![image](https://user-images.githubusercontent.com/63189561/84084404-181ab180-a9ec-11ea-960a-82f21ff2370f.png)

My ongamemodeinit !
![image](https://user-images.githubusercontent.com/63189561/84084463-2ff23580-a9ec-11ea-9681-035f8a1d2e1e.png)

I use latest version.

**Comment by urShadow** [comment]
Try that. 

https://github.com/urShadow/Pawn.CMD/issues/23

**Comment by qSorin** [comment]
Nope, it's not work...
![image](https://user-images.githubusercontent.com/63189561/84131755-a7a47c80-aa4d-11ea-8998-bbe92dfeb34e.png)

@urShadow

**Comment by urShadow** [comment]
Try to register aliases via "alias" macro instead of manual calling PC_RegAlias.

**Comment by qSorin** [comment]
It's work. Thanks you!

**Comment by qSorin** [comment]
Nope, it's not work with alias. it's a same problem!

![image](https://user-images.githubusercontent.com/63189561/84134016-9e68df00-aa50-11ea-9e67-adaaefd501d7.png)

**Comment by urShadow** [comment]
Can you attach server_log.txt?

**Comment by qSorin** [comment]
Of course
[server_log.txt](https://github.com/urShadow/Pawn.CMD/files/4752424/server_log.txt)

**Comment by urShadow** [comment]
I think you try to register an alias for command that does not exist.

**Comment by qSorin** [comment]
Yea.. my problem is solved. Thanks you @urShadow !
