### ISSUE TITLE
(v3.3.2) HandleCommand - backtrace and crash

### ISSUE THREAD

**Issue by AliLogic** [urShadow/Pawn.CMD#26]
Hi, I had this weird issue in my script a couple of times but I haven't been able to narrow down to what's the root cause of it.  The issue is this and it does sometimes crash the server, other times it doesn't.  Please provide information on how and what does the HandleCommand issue means and how to, if there is any solution to detect the "<unknown file>:0" issue. I believe it might be because of the new plugin library that you use because I haven't had the issue with it.

I was using 3.3.2, but I have switched to 3.3.3 after this issue.  I will report if it still occurs because I have no idea how to reproduce it.

```c
[18:25:29] [debug] Run time error 4: "Array index out of bounds"
[18:25:29] [debug]  Attempted to read/write array element at index 115 in array of size 100
[18:25:29] [debug] AMX backtrace:
[18:25:29] [debug] #0 003ba4a8 in ?? (... <28 arguments>) at C:\some\fake\path\script.amx
[18:25:29] [debug] #1 00000075 in public pc_cmd_asay () at <unknown file>:0
[18:25:29] [Pawn.CMD] HandleCommand: Call: amx function (7) error 4```

Thanks!

**Comment by urShadow** [comment]
> [18:25:29] [debug]  Attempted to read/write array element at index 115 in array of size 100

> in public pc_cmd_asay

This.

**Comment by AliLogic** [comment]
I've looked into the code, but nothing is suspicious in it.  And there's no explicit information either.

**Comment by MaxAndolini** [comment]
I am getting this too;

[Pawn.CMD] HandleCommand: Call: amx_Push(struct tagAMX *:03380570, int:16): Stack/heap collision (insufficient stack size) (3)

**Comment by urShadow** [comment]
It is internal AMX errors (or errors in your Pawn code).

Pawn.CMD just informs you about them (similarly to crashdetect plugin).

**Comment by MaxAndolini** [comment]
> It is internal AMX errors (or errors in your Pawn code).
> 
> Pawn.CMD just informs you about them (similarly to crashdetect plugin).

Yea, fixed.
