### ISSUE TITLE
y_hooks

### ISSUE THREAD

**Issue by TomasM65** [urShadow/Pawn.CMD#3]
Hello 
I'm work with YSI includes and concret include y_hook with Pawn.CMD worked problem. 
When I compilare code so no't working command.

**Comment by urShadow** [comment]
I need more information.

**Comment by TomasM65** [comment]
when I calling existing command, so command no call and not writen error warning. Commands not function.

**Comment by TomasM65** [comment]
Sorry for my bat repport but on my code no't functioned. I'm download new update your plugin and all it works.
