### ISSUE TITLE
Flags not working

### ISSUE THREAD

**Issue by Sasuke-Uchiha** [urShadow/Pawn.CMD#4]
I tried setting a flag ANIMATIONS and it won't work, the enum for it is

`enum {
	ANIMATIONS
}`

**Comment by IstuntmanI** [comment]
Because the first value of an enumerator is 0, so for it to work you would need to do, at least:
```pawn
enum
{
    ANIMATIONS = 1
}
```

If you plan to add more flags in the future in that enumerator, it is recommended to do
```pawn
enum ( <<= 1 )
{
    ANIMATIONS = 1,
    FLAG_2,
    FLAG_3,
}
```
So the first flag (ANIMATIONS) will have the value 0b1, the next will be 0b10, then the next will be 0b100.

**Comment by Sasuke-Uchiha** [comment]
Thanks for the info and help :)

It's fixed now.
