### ISSUE TITLE
PC_EmulateCommand seems to be not working

### ISSUE THREAD

**Issue by Bios-Marcel** [urShadow/Pawn.CMD#5]
Admins should be able to open a config dialog by typing /cp , and whenever they use Button 1 (Response == 1) the dialog should be reopend after the tasks are done, but nothing is happening, here is my code:

https://gist.github.com/Bios-Marcel/8e56a942640a6cac70001e7a909b49e6

**Comment by IstuntmanI** [comment]
As far as I know, PC_EmulateCommand requires a "**/**" before the command name.

So
```pawn
PC_EmulateCommand(playerid, "cp");
```
becomes
```pawn
PC_EmulateCommand(playerid, "/cp");
```

By the way, in the alias line you added a "controlapnel" alias, you mistyped it.

**Comment by Bios-Marcel** [comment]
Oh, you were right, i didn't expect that. Someone should write a documentation / wiki to this Plugin :D
