### ISSUE TITLE
Freezes Randomly

### ISSUE THREAD

**Issue by marcelog09** [urShadow/Pawn.CMD#59]
My server freezes randomly. In the event of a freeze, I am forced to turn it off and on again, as it does not defrost on its own. The 'Crashdetect' does not report any from gamemode function that may be "slow" at the time of freezing.

Q: How do I know the problem may have to do with this plugin (Pawn.CMD)?
A: I tested the server without this plugin (Pawn.CMD) and the problem did not occur.

plugin version used: 3.4.0 (SA-MP)
Operating System: Windows Server 2019
Plugins used: 
sampvoice
discord-connector 
pawnraknet 
log-plugin 
mysql 
sscanf 
CTime 
MapAndreas 
streamer 
pawnregex 
pawn-memory 
SAMPSON

**Comment by FreddieCrew** [comment]
Please attach the server_log.txt file here.
