### ISSUE TITLE
Skipping legacy plugin 'pawncmd'; There is an open.mp compatible version you can find here: https://github.com/katursis/Pawn.CMD/releases , make sure to download x.x.x-omp version

### ISSUE THREAD

**Issue by IliesAlexandruBogdan** [urShadow/Pawn.CMD#61]
Hello, i want to run Open.MP project and when i start server i recieve this error: 

Skipping legacy plugin 'pawncmd'; There is an open.mp compatible version you can find here: https://github.com/katursis/Pawn.CMD/releases , make sure to download x.x.x-omp version

I'm use pawncmd 3.3.6 omp version and i have same problem with the last pawncmd version

**Comment by FreddieCrew** [comment]
Use the [3.4.0-omp](https://github.com/katursis/Pawn.CMD/releases/tag/3.4.0-omp) version as Pawn.CMD utilizes memory hacking methods, you'll need to use this version.

**Comment by IliesAlexandruBogdan** [comment]
@FreddieCrew I use 3.4.0-omp and same problem

**Comment by FreddieCrew** [comment]
> @FreddieCrew I use 3.4.0-omp and same problem

Place it inside 'components' folder, not 'plugins' folder.

**Comment by IliesAlexandruBogdan** [comment]
Thanks a lot, it works.
