### ISSUE TITLE
Missing natives.

### ISSUE THREAD

**Issue by sicariodll** [urShadow/Pawn.CMD#63]
Some natives from YSF plugin isn't added to OMP. (Like SetPlayerChatBubbleForPlayer.) 

Are the missing natives planned to be added on next release?

Thank you.

**Comment by FreddieCrew** [comment]
Wrong repository. This is the Pawn.CMD repository, not the YSF repository.

**Comment by sicariodll** [comment]
Sorry for that, confussion :)
