### ISSUE TITLE
Commands Not Working 3.1.4

### ISSUE THREAD

**Issue by MaxAndolini** [urShadow/Pawn.CMD#7]
Pawn CMD plugin version 3.1.2 work but 3.1.4 commands not working. What is the reason for this?

**Comment by urShadow** [comment]
Windows or Linux?

**Comment by MaxAndolini** [comment]
Windows 10 Pro

**Comment by urShadow** [comment]
If you have OnPlayerCommandText in a gamemode and it always returns 1, you have to remove it.

Example:
```
public OnPlayerCommandText(playerid, cmdtext[])
{
    return 1;
}
```
